
- name: Configure beats ilm policies
  become: true
  ansible.builtin.template:
    src: ilm-policy.json.j2
    dest: /etc/auditbeat/ilm-policy.json
    mode: "0640"

- name: Write beat config
  become: true
  ansible.builtin.template:
    src: "auditbeat_config.yml.j2"
    dest: /etc/auditbeat/auditbeat.yml
    mode: "0644"